
import React, { useState, useCallback } from 'react';
import SEOWrapper from '../../components/SEOWrapper';
import { Lock, Copy, RefreshCw, Check } from 'lucide-react';

const PasswordGenerator: React.FC = () => {
  const [length, setLength] = useState(16);
  const [includeUpper, setIncludeUpper] = useState(true);
  const [includeNumbers, setIncludeNumbers] = useState(true);
  const [includeSymbols, setIncludeSymbols] = useState(true);
  const [password, setPassword] = useState('');
  const [copied, setCopied] = useState(false);

  const generatePassword = useCallback(() => {
    let charset = 'abcdefghijklmnopqrstuvwxyz';
    if (includeUpper) charset += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    if (includeNumbers) charset += '0123456789';
    if (includeSymbols) charset += '!@#$%^&*()_+~`|}{[]:;?><,./-=';

    let retVal = '';
    for (let i = 0, n = charset.length; i < length; ++i) {
      retVal += charset.charAt(Math.floor(Math.random() * n));
    }
    setPassword(retVal);
    setCopied(false);
  }, [length, includeUpper, includeNumbers, includeSymbols]);

  React.useEffect(() => {
    generatePassword();
  }, [generatePassword]);

  const copyToClipboard = () => {
    navigator.clipboard.writeText(password);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const seoData = {
    title: 'Professional Password Generator: Create Secure, Hack-Proof Passwords Online',
    introduction: 'Protect your digital identity with Habix Media\'s Secure Password Generator. Create high-entropy, randomized strings that are resistant to brute-force attacks and social engineering.',
    howToUse: [
      'Slide the length bar to select between 8 and 32 characters.',
      'Select complexity requirements like Uppercase, Numbers, and Special Symbols.',
      'Observe the instant update of the password string.',
      'Click the Copy button to securely transfer the password to your manager.'
    ],
    benefits: [
      'Cryptographic Randomness: Our generator uses browser-based randomization for high security.',
      'Local Generation: Your passwords are created in your browser; they never touch our servers.',
      'Custom Complexity: Balance security with memorability by toggling specific character types.',
      'Zero Tracking: We do not log or store any passwords generated on this platform.'
    ],
    detailedArticle: `In an era dominated by frequent data breaches, the strength of your password is your first line of defense. A common mistake users make is using easily guessable phrases or reusing the same password across multiple sites. This practice makes you vulnerable to "credential stuffing" attacks.

Habix Media's Random Password Generator is designed to combat these threats by providing truly unique, high-entropy strings. 

What makes a password secure?
1. Length: Every character added increases the complexity exponentially. We recommend at least 16 characters for critical accounts.
2. Diversity: Mixing uppercase letters, lowercase letters, numbers, and symbols significantly increases the "work factor" required for a hacker to crack your code.
3. Unpredictability: Humans are bad at randomness. We tend to follow patterns. Our tool removes human bias entirely.

Security Best Practices:
Always use a dedicated password manager (like Bitwarden, LastPass, or 1Password) to store the complex strings generated by our tool. Never write passwords down or store them in unencrypted text files. By combining our generator with a trusted vault, you ensure your online presence remains impenetrable. At Habix Media, we provide this utility for free to help foster a safer, more secure internet for everyone.`
  };

  return (
    <SEOWrapper content={seoData}>
      <div className="p-8 md:p-12">
        <div className="max-w-xl mx-auto space-y-8">
          <div className="text-center">
            <div className="w-16 h-16 bg-slate-100 text-slate-600 rounded-2xl flex items-center justify-center mx-auto mb-4">
              <Lock size={32} />
            </div>
            <h2 className="text-2xl font-bold">Secure Password Generator</h2>
          </div>

          <div className="relative group">
            <input 
              type="text" 
              readOnly 
              value={password}
              className="w-full bg-slate-50 p-6 rounded-2xl text-2xl font-mono text-center tracking-wider border border-slate-200 focus:outline-none"
            />
            <div className="absolute right-4 top-1/2 -translate-y-1/2 flex space-x-2">
              <button 
                onClick={generatePassword}
                className="p-2 text-slate-400 hover:text-indigo-600 transition-colors"
                title="Regenerate"
              >
                <RefreshCw size={24} />
              </button>
              <button 
                onClick={copyToClipboard}
                className="p-2 text-slate-400 hover:text-indigo-600 transition-colors"
                title="Copy"
              >
                {copied ? <Check size={24} className="text-green-500" /> : <Copy size={24} />}
              </button>
            </div>
          </div>

          <div className="space-y-6">
            <div className="space-y-3">
              <div className="flex justify-between items-center text-sm font-medium">
                <span className="text-slate-600">Password Length</span>
                <span className="text-indigo-600 bg-indigo-50 px-3 py-1 rounded-full">{length} chars</span>
              </div>
              <input 
                type="range" 
                min="8" 
                max="32" 
                value={length}
                onChange={(e) => setLength(parseInt(e.target.value))}
                className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-indigo-600"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              {[
                { label: 'Uppercase', state: includeUpper, set: setIncludeUpper },
                { label: 'Numbers', state: includeNumbers, set: setIncludeNumbers },
                { label: 'Symbols', state: includeSymbols, set: setIncludeSymbols },
              ].map((opt) => (
                <button
                  key={opt.label}
                  onClick={() => opt.set(!opt.state)}
                  className={`p-4 rounded-xl border text-sm font-bold transition-all ${
                    opt.state 
                    ? 'border-indigo-600 bg-indigo-50 text-indigo-600' 
                    : 'border-slate-200 text-slate-400'
                  }`}
                >
                  {opt.label}
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>
    </SEOWrapper>
  );
};

export default PasswordGenerator;
