
import React from 'react';

const Terms: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-20 prose prose-slate">
      <h1 className="text-4xl font-bold mb-8">Terms and Conditions</h1>
      <p className="text-slate-500 italic mb-8">Last Updated: May 20, 2024</p>
      
      <section className="mb-8">
        <h2 className="text-2xl font-bold">1. Acceptance of Terms</h2>
        <p>By accessing and using Habix Media, you accept and agree to be bound by the terms and provision of this agreement. In addition, when using these particular services, you shall be subject to any posted guidelines or rules applicable to such services.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold">2. Provision of Service</h2>
        <p>Habix Media provides various digital tools for free. We reserve the right to modify or discontinue any tool or service without notice. You agree that Habix Media shall not be liable to you or any third party for any modification, suspension, or discontinuance of the service.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold">3. User Conduct</h2>
        <p>You agree to use Habix Media only for lawful purposes. You are prohibited from using the site to transmit any material that is illegal, harmful, or violates the rights of others. This includes attempting to bypass any security measures or usage limits on our AI tools.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold">4. Disclaimer of Warranty</h2>
        <p>Our tools are provided "as is" and without warranty of any kind. We do not guarantee that the results generated by our calculators or AI tools will be 100% accurate or fit for any specific purpose. Use these tools at your own risk.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold">5. Limitation of Liability</h2>
        <p>Habix Media shall not be liable for any direct, indirect, incidental, special or consequential damages resulting from the use or the inability to use the service or for cost of procurement of substitute goods and services.</p>
      </section>
    </div>
  );
};

export default Terms;
